/**
 * VSCode tasks.json auto-provisioning
 *
 * Stop Hook から毎ターン呼ばれる想定。冪等で低コスト。
 *
 * 狙い: Throughline をグローバル導入したユーザーが VSCode で任意のプロジェクトを
 * 開いたとき、初回のアシスタント応答完了時点で .vscode/tasks.json に
 * "Throughline Monitor" タスクを自動登録し、次回フォルダを開いた瞬間に
 * 専用ターミナルで token-monitor を自動起動させる。
 *
 * 2 段構え:
 *  - tasks.json が無い or 純 JSON としてパース可能 → 作成 / 安全にマージ
 *  - JSONC フィーチャ (コメント・末尾カンマ) を検出 → 触らず手動案内 1 回のみ
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync, renameSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join, dirname, isAbsolute } from 'node:path';

const MONITOR_LABEL = 'Throughline Monitor';
const JSONC_MARKER_FILENAME = '.throughline-jsonc-noted';
const GITIGNORE_MARKER_FILENAME = '.throughline-gitignore-noted';

/**
 * VSCode 系エディタが動いているかを env から推定する。
 * Cursor / VSCodium / Windsurf でも VSCODE_* は立つ。同じ tasks.json を読むので OK。
 */
export function detectVsCode(env) {
  return (
    env.TERM_PROGRAM === 'vscode' ||
    Boolean(env.VSCODE_PID) ||
    Boolean(env.VSCODE_IPC_HOOK_CLI)
  );
}

/**
 * 入力テキストに JSONC フィーチャ (コメント・末尾カンマ) が含まれるかを判定する。
 * 文字列リテラル内の偽陽性を避けるため軽量トークナイズする。
 */
export function detectJsoncFeatures(text) {
  let inString = false;
  let quote = '';
  let prevNonSpace = '';
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inString) {
      if (c === '\\') {
        i++;
        continue;
      }
      if (c === quote) {
        inString = false;
      }
      continue;
    }
    if (c === '"' || c === "'") {
      inString = true;
      quote = c;
      prevNonSpace = c;
      continue;
    }
    if (c === '/' && text[i + 1] === '/') return true;
    if (c === '/' && text[i + 1] === '*') return true;
    if (c === ']' || c === '}') {
      if (prevNonSpace === ',') return true;
    }
    if (c !== ' ' && c !== '\t' && c !== '\n' && c !== '\r') {
      prevNonSpace = c;
    }
  }
  return false;
}

/**
 * テキストから JSON のインデントスタイルを推定する。
 * 最初にネストされた行の先頭空白を見る。検出できなければ 2 スペース。
 */
export function detectIndent(text) {
  const match = text.match(/\n([ \t]+)\S/);
  if (match) return match[1];
  return '  ';
}

/**
 * tasks 配列内で Throughline Monitor 相当のタスクの index を返す。
 * ユーザーが label をリネームしても command/args に "throughline" + "monitor" が
 * あれば同一タスクとみなす。見つからない場合は -1。
 */
export function findMonitorTaskIndex(obj) {
  const tasks = obj?.tasks;
  if (!Array.isArray(tasks)) return -1;
  for (let i = 0; i < tasks.length; i++) {
    const t = tasks[i];
    if (!t || typeof t !== 'object') continue;
    if (t.label === MONITOR_LABEL) return i;
    const invocation = [t.command, ...(Array.isArray(t.args) ? t.args : [])]
      .filter((s) => typeof s === 'string')
      .join(' ')
      .toLowerCase();
    if (invocation.includes('throughline') && invocation.includes('monitor')) {
      return i;
    }
  }
  return -1;
}

export function hasMonitorTask(obj) {
  return findMonitorTaskIndex(obj) >= 0;
}

/**
 * 既存の Monitor タスクが「別環境（別 OS / 別 install 場所）の絶対パスを参照していて
 * 現在の環境では起動できない」状態かを判定する。
 *
 * 判定基準:
 *   - command が絶対パスかつ existsSync(command) === false → 壊れている
 *   - args の中に絶対パスの .mjs / .js / .cjs があり、それが存在しない → 壊れている
 *
 * 相対パス（"node" / "throughline" 等の PATH 解決前提）は判定対象外。
 * ユーザーが手動で PATH 解決型に書き換えたケースを誤って上書きしないため。
 */
export function isMonitorTaskBroken(task) {
  if (!task || typeof task !== 'object') return false;
  if (typeof task.command === 'string' && isAbsolute(task.command) && !existsSync(task.command)) {
    return true;
  }
  if (Array.isArray(task.args)) {
    for (const a of task.args) {
      if (
        typeof a === 'string' &&
        isAbsolute(a) &&
        /\.(mjs|js|cjs)$/.test(a) &&
        !existsSync(a)
      ) {
        return true;
      }
    }
  }
  return false;
}

/**
 * 生成する VSCode タスク定義を組み立てる。
 *
 * type: 'shell' を選ぶ理由:
 *   VSCode の type: 'process' は子プロセスの stdout を生パイプで渡すため、
 *   isTTY=false となり真の columns が取れず、`\x1b[2J\x1b[H` や alt screen も
 *   期待通りに動かず、モニターの行描画が毎ティック積み上がる症状を引き起こす。
 *   type: 'shell' なら VSCode が PTY を張って xterm.js ベースの疑似端末を与え、
 *   isTTY=true で真の幅が取れ、resize イベントも発火する。
 *
 *   Windows の .cmd shim リスクは「command / args を shell の実行ファイル
 *   (cmd.exe / bash) に絶対パスで渡す」ので消えている。command に node.exe の
 *   絶対パス、args に throughline.mjs の絶対パスと 'monitor' を入れ、shell
 *   (cmd.exe や pwsh) がそのまま起動するだけ。
 */
export function buildMonitorTask(throughlineBin) {
  return {
    label: MONITOR_LABEL,
    detail: 'Auto-generated by Throughline. Opens token-monitor in a dedicated terminal when the folder is opened.',
    type: 'shell',
    command: process.execPath,
    args: [throughlineBin, 'monitor'],
    isBackground: true,
    presentation: {
      reveal: 'always',
      panel: 'dedicated',
      group: 'throughline',
      close: false,
      echo: false,
      focus: false,
      showReuseMessage: false,
      clear: true,
    },
    runOptions: { runOn: 'folderOpen' },
    problemMatcher: [],
  };
}

/**
 * グローバル install 時の node_modules/throughline/bin/throughline.mjs、
 * もしくはローカル開発時の <repo>/bin/throughline.mjs の絶対パスを返す。
 * 見つからない場合は null。
 */
export function resolveThroughlineBin() {
  try {
    const path = fileURLToPath(new URL('../bin/throughline.mjs', import.meta.url));
    if (existsSync(path)) return path;
  } catch {
    // fileURLToPath 失敗は想定外だが、その場合は null を返して skip に回す
  }
  return null;
}

function atomicWrite(targetPath, contents) {
  const tmp = `${targetPath}.tmp-${process.pid}-${Date.now()}`;
  writeFileSync(tmp, contents);
  renameSync(tmp, targetPath);
}

/**
 * tasks.json を「今まさに作成/マージした」瞬間にユーザー向けへ送る通知テキスト。
 *
 * SessionStart / UserPromptSubmit の stdout は Claude Code に additional context として
 * 取り込まれる。<system-reminder> で包んで Claude に「これをユーザーに伝える」ことを
 * 明示しておくことで、新規プロジェクト初回セットアップ直後にユーザーへ
 * 「Reload Window が必要」を即時通知できる。
 *
 * 通知するのは action が 'created' か 'merged' の場合のみ。既に存在した場合は
 * セットアップ済みのため沈黙する（冪等性）。
 */
export function buildSetupNotice(action) {
  if (action === 'created' || action === 'merged') {
    return (
      '<system-reminder>\n' +
      'Throughline: このプロジェクトに token-monitor の自動起動設定を追加しました (.vscode/tasks.json)。\n' +
      '今すぐ monitor を起動するには、VSCode のコマンドパレット (Ctrl+Shift+P) から\n' +
      '  Developer: Reload Window\n' +
      'を実行してください。次回以降はフォルダを開いた瞬間に自動起動します。\n' +
      '\n' +
      'このお知らせは今このプロジェクトで初回セットアップが完了したためだけに 1 度だけ流れています。\n' +
      '必ずユーザー（あなたの対話相手）に日本語でそのまま伝えてください。\n' +
      '</system-reminder>\n'
    );
  }
  if (action === 'repaired') {
    return (
      '<system-reminder>\n' +
      'Throughline: .vscode/tasks.json に登録されていた token-monitor タスクが\n' +
      '別環境（別 OS / 別 install 場所）の絶対パスを参照していたため、現環境向けに自動修復しました。\n' +
      '反映するには VSCode のコマンドパレット (Ctrl+Shift+P) から\n' +
      '  Developer: Reload Window\n' +
      'を実行してください。\n' +
      '\n' +
      '必ずユーザー（あなたの対話相手）に日本語でそのまま伝えてください。\n' +
      '</system-reminder>\n'
    );
  }
  return null;
}

function emitSetupNotice(action) {
  const text = buildSetupNotice(action);
  if (text) process.stdout.write(text);
}

/**
 * `.vscode/tasks.json` が gitignore 推奨対象か判定する。
 *
 * 推奨条件:
 *   - cwd が git リポジトリ (`.git/` がある) かつ
 *   - `.gitignore` に `.vscode/tasks.json` 相当のエントリが無い
 *
 * 単独プロジェクト (.git なし) は判定対象外 (false を返す)。共有しないので
 * gitignore の必要性そのものが無いため。
 *
 * @param {string} cwd
 * @returns {boolean}
 */
export function shouldRecommendGitignore(cwd) {
  const gitDir = join(cwd, '.git');
  if (!existsSync(gitDir)) return false;

  const gitignorePath = join(cwd, '.gitignore');
  if (!existsSync(gitignorePath)) return true;

  const content = readFileSync(gitignorePath, 'utf8');
  const lines = content.split(/\r?\n/);
  for (const raw of lines) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    // 否定 (!) は除外しない: "!.vscode/tasks.json" は明示的に追跡したい意図なので推奨を出すべき
    if (line.startsWith('!')) continue;
    // .vscode 全体除外 / tasks.json 単独除外 / .vscode/* どれかを含むか
    if (line === '.vscode' || line === '.vscode/' || line === '/.vscode' || line === '/.vscode/') return false;
    if (line === '.vscode/*' || line === '.vscode/**') return false;
    if (line === '.vscode/tasks.json' || line === '/.vscode/tasks.json') return false;
  }
  return true;
}

function emitGitignoreRecommendationOnce(vscodeDir) {
  const markerPath = join(vscodeDir, GITIGNORE_MARKER_FILENAME);
  if (existsSync(markerPath)) return;
  process.stdout.write(
    '<system-reminder>\n' +
    'Throughline ヒント: .vscode/tasks.json には現環境の絶対パス (node 実行ファイル / throughline.mjs)\n' +
    'が書き込まれます。共有リポジトリで commit すると別 OS / 別 install 場所のメンバーで起動失敗の\n' +
    '原因になるため、.gitignore に以下のいずれかを追加することを推奨します:\n' +
    '\n' +
    '  .vscode/tasks.json     # tasks.json だけ除外 (settings.json 等は共有可)\n' +
    '  .vscode/                # .vscode 配下を全部除外\n' +
    '\n' +
    'なお Throughline v0.3.23+ は別環境の絶対パスが焼き込まれた tasks.json を\n' +
    '自動修復するため、commit してしまっても致命的ではありません。あくまで推奨です。\n' +
    '\n' +
    'この通知はプロジェクトごとに 1 度だけ流れます。必ずユーザー（あなたの対話相手）に日本語でそのまま伝えてください。\n' +
    '</system-reminder>\n'
  );
  try {
    writeFileSync(markerPath, `${new Date().toISOString()}\n`);
  } catch (err) {
    const msg = err instanceof Error ? err.message : 'unknown';
    process.stderr.write(`[throughline] failed to write gitignore marker: ${msg}\n`);
  }
}

function emitJsoncGuidanceOnce(vscodeDir) {
  const markerPath = join(vscodeDir, JSONC_MARKER_FILENAME);
  if (existsSync(markerPath)) return;
  process.stderr.write(
    `[throughline] .vscode/tasks.json contains JSONC features (comments or trailing commas). ` +
      `Auto-edit is unsafe on this file — add the Throughline Monitor task manually. ` +
      `See README for the snippet. This notice prints once per project.\n`,
  );
  try {
    writeFileSync(markerPath, `${new Date().toISOString()}\n`);
  } catch (err) {
    const msg = err instanceof Error ? err.message : 'unknown';
    process.stderr.write(`[throughline] failed to write JSONC marker: ${msg}\n`);
  }
}

/**
 * VSCode の tasks.json に Throughline Monitor タスクを（必要なら）自動登録する。
 *
 * 既存タスクが別環境の絶対パスを参照していて現環境で起動できない場合は
 * command/args だけを差し替えて修復する（label / presentation 等のユーザー
 * カスタマイズは保持）。
 *
 * @param {{cwd?: string, env?: NodeJS.ProcessEnv, throughlineBin?: string | null}} opts
 * @returns {{
 *   action: 'created' | 'merged' | 'repaired' | 'already_present' | 'skipped',
 *   reason?: string,
 *   path?: string,
 * }}
 */
export function ensureMonitorTaskFile(opts = {}) {
  const env = opts.env ?? process.env;
  const cwd = opts.cwd;

  if (env.THROUGHLINE_NO_VSCODE === '1') {
    return { action: 'skipped', reason: 'opt_out' };
  }
  if (!cwd || !existsSync(cwd)) {
    return { action: 'skipped', reason: 'no_cwd' };
  }
  if (!detectVsCode(env)) {
    return { action: 'skipped', reason: 'not_vscode' };
  }

  const bin = opts.throughlineBin !== undefined
    ? opts.throughlineBin
    : resolveThroughlineBin();
  if (!bin) {
    return { action: 'skipped', reason: 'no_bin' };
  }

  const vscodeDir = join(cwd, '.vscode');
  const tasksPath = join(vscodeDir, 'tasks.json');

  if (!existsSync(tasksPath)) {
    if (!existsSync(vscodeDir)) mkdirSync(vscodeDir, { recursive: true });
    const obj = { version: '2.0.0', tasks: [buildMonitorTask(bin)] };
    atomicWrite(tasksPath, JSON.stringify(obj, null, 2) + '\n');
    emitSetupNotice('created');
    if (shouldRecommendGitignore(cwd)) emitGitignoreRecommendationOnce(vscodeDir);
    return { action: 'created', path: tasksPath };
  }

  const text = readFileSync(tasksPath, 'utf8');

  if (detectJsoncFeatures(text)) {
    emitJsoncGuidanceOnce(vscodeDir);
    return { action: 'skipped', reason: 'jsonc_unsupported', path: tasksPath };
  }

  let obj;
  try {
    obj = JSON.parse(text);
  } catch {
    return { action: 'skipped', reason: 'parse_error', path: tasksPath };
  }

  const existingIdx = findMonitorTaskIndex(obj);
  if (existingIdx >= 0) {
    const existing = obj.tasks[existingIdx];
    if (isMonitorTaskBroken(existing)) {
      const fresh = buildMonitorTask(bin);
      const repaired = {
        ...existing,
        type: fresh.type,
        command: fresh.command,
        args: fresh.args,
      };
      const indent = detectIndent(text);
      const nextTasks = [...obj.tasks];
      nextTasks[existingIdx] = repaired;
      const nextObj = { ...obj, version: obj.version ?? '2.0.0', tasks: nextTasks };
      atomicWrite(tasksPath, JSON.stringify(nextObj, null, indent) + '\n');
      emitSetupNotice('repaired');
      if (shouldRecommendGitignore(cwd)) emitGitignoreRecommendationOnce(vscodeDir);
      return { action: 'repaired', path: tasksPath };
    }
    return { action: 'already_present', path: tasksPath };
  }

  const indent = detectIndent(text);
  const nextObj = {
    ...obj,
    version: obj.version ?? '2.0.0',
    tasks: [...(Array.isArray(obj.tasks) ? obj.tasks : []), buildMonitorTask(bin)],
  };
  atomicWrite(tasksPath, JSON.stringify(nextObj, null, indent) + '\n');
  emitSetupNotice('merged');
  if (shouldRecommendGitignore(cwd)) emitGitignoreRecommendationOnce(vscodeDir);
  return { action: 'merged', path: tasksPath };
}
