/**
 * VSCode tasks.json auto-provisioning
 *
 * Stop Hook から毎ターン呼ばれる想定。冪等で低コスト。
 *
 * 狙い: Throughline をグローバル導入したユーザーが VSCode で任意のプロジェクトを
 * 開いたとき、初回のアシスタント応答完了時点で .vscode/tasks.json に
 * "Throughline Monitor" タスクを自動登録し、次回フォルダを開いた瞬間に
 * 専用ターミナルで token-monitor を自動起動させる。
 *
 * 2 段構え:
 *  - tasks.json が無い or 純 JSON としてパース可能 → 作成 / 安全にマージ
 *  - JSONC フィーチャ (コメント・末尾カンマ) を検出 → 触らず手動案内 1 回のみ
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync, renameSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join, dirname } from 'node:path';

const MONITOR_LABEL = 'Throughline Monitor';
const JSONC_MARKER_FILENAME = '.throughline-jsonc-noted';

/**
 * VSCode 系エディタが動いているかを env から推定する。
 * Cursor / VSCodium / Windsurf でも VSCODE_* は立つ。同じ tasks.json を読むので OK。
 */
export function detectVsCode(env) {
  return (
    env.TERM_PROGRAM === 'vscode' ||
    Boolean(env.VSCODE_PID) ||
    Boolean(env.VSCODE_IPC_HOOK_CLI)
  );
}

/**
 * 入力テキストに JSONC フィーチャ (コメント・末尾カンマ) が含まれるかを判定する。
 * 文字列リテラル内の偽陽性を避けるため軽量トークナイズする。
 */
export function detectJsoncFeatures(text) {
  let inString = false;
  let quote = '';
  let prevNonSpace = '';
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inString) {
      if (c === '\\') {
        i++;
        continue;
      }
      if (c === quote) {
        inString = false;
      }
      continue;
    }
    if (c === '"' || c === "'") {
      inString = true;
      quote = c;
      prevNonSpace = c;
      continue;
    }
    if (c === '/' && text[i + 1] === '/') return true;
    if (c === '/' && text[i + 1] === '*') return true;
    if (c === ']' || c === '}') {
      if (prevNonSpace === ',') return true;
    }
    if (c !== ' ' && c !== '\t' && c !== '\n' && c !== '\r') {
      prevNonSpace = c;
    }
  }
  return false;
}

/**
 * テキストから JSON のインデントスタイルを推定する。
 * 最初にネストされた行の先頭空白を見る。検出できなければ 2 スペース。
 */
export function detectIndent(text) {
  const match = text.match(/\n([ \t]+)\S/);
  if (match) return match[1];
  return '  ';
}

/**
 * tasks 配列に Throughline Monitor 相当のタスクが含まれるか判定する。
 * ユーザーが label をリネームしても command/args に "throughline" + "monitor" が
 * あれば同一タスクとみなす。
 */
export function hasMonitorTask(obj) {
  const tasks = obj?.tasks;
  if (!Array.isArray(tasks)) return false;
  for (const t of tasks) {
    if (!t || typeof t !== 'object') continue;
    if (t.label === MONITOR_LABEL) return true;
    const invocation = [t.command, ...(Array.isArray(t.args) ? t.args : [])]
      .filter((s) => typeof s === 'string')
      .join(' ')
      .toLowerCase();
    if (invocation.includes('throughline') && invocation.includes('monitor')) {
      return true;
    }
  }
  return false;
}

/**
 * 生成する VSCode タスク定義を組み立てる。
 *
 * type: 'shell' を選ぶ理由:
 *   VSCode の type: 'process' は子プロセスの stdout を生パイプで渡すため、
 *   isTTY=false となり真の columns が取れず、`\x1b[2J\x1b[H` や alt screen も
 *   期待通りに動かず、モニターの行描画が毎ティック積み上がる症状を引き起こす。
 *   type: 'shell' なら VSCode が PTY を張って xterm.js ベースの疑似端末を与え、
 *   isTTY=true で真の幅が取れ、resize イベントも発火する。
 *
 *   Windows の .cmd shim リスクは「command / args を shell の実行ファイル
 *   (cmd.exe / bash) に絶対パスで渡す」ので消えている。command に node.exe の
 *   絶対パス、args に throughline.mjs の絶対パスと 'monitor' を入れ、shell
 *   (cmd.exe や pwsh) がそのまま起動するだけ。
 */
export function buildMonitorTask(throughlineBin) {
  return {
    label: MONITOR_LABEL,
    detail: 'Auto-generated by Throughline. Opens token-monitor in a dedicated terminal when the folder is opened.',
    type: 'shell',
    command: process.execPath,
    args: [throughlineBin, 'monitor'],
    isBackground: true,
    presentation: {
      reveal: 'always',
      panel: 'dedicated',
      group: 'throughline',
      close: false,
      echo: false,
      focus: false,
      showReuseMessage: false,
      clear: true,
    },
    runOptions: { runOn: 'folderOpen' },
    problemMatcher: [],
  };
}

/**
 * グローバル install 時の node_modules/throughline/bin/throughline.mjs、
 * もしくはローカル開発時の <repo>/bin/throughline.mjs の絶対パスを返す。
 * 見つからない場合は null。
 */
export function resolveThroughlineBin() {
  try {
    const path = fileURLToPath(new URL('../bin/throughline.mjs', import.meta.url));
    if (existsSync(path)) return path;
  } catch {
    // fileURLToPath 失敗は想定外だが、その場合は null を返して skip に回す
  }
  return null;
}

function atomicWrite(targetPath, contents) {
  const tmp = `${targetPath}.tmp-${process.pid}-${Date.now()}`;
  writeFileSync(tmp, contents);
  renameSync(tmp, targetPath);
}

function emitJsoncGuidanceOnce(vscodeDir) {
  const markerPath = join(vscodeDir, JSONC_MARKER_FILENAME);
  if (existsSync(markerPath)) return;
  process.stderr.write(
    `[throughline] .vscode/tasks.json contains JSONC features (comments or trailing commas). ` +
      `Auto-edit is unsafe on this file — add the Throughline Monitor task manually. ` +
      `See README for the snippet. This notice prints once per project.\n`,
  );
  try {
    writeFileSync(markerPath, `${new Date().toISOString()}\n`);
  } catch (err) {
    const msg = err instanceof Error ? err.message : 'unknown';
    process.stderr.write(`[throughline] failed to write JSONC marker: ${msg}\n`);
  }
}

/**
 * VSCode の tasks.json に Throughline Monitor タスクを（必要なら）自動登録する。
 *
 * @param {{cwd?: string, env?: NodeJS.ProcessEnv, throughlineBin?: string | null}} opts
 * @returns {{
 *   action: 'created' | 'merged' | 'already_present' | 'skipped',
 *   reason?: string,
 *   path?: string,
 * }}
 */
export function ensureMonitorTaskFile(opts = {}) {
  const env = opts.env ?? process.env;
  const cwd = opts.cwd;

  if (env.THROUGHLINE_NO_VSCODE === '1') {
    return { action: 'skipped', reason: 'opt_out' };
  }
  if (!cwd || !existsSync(cwd)) {
    return { action: 'skipped', reason: 'no_cwd' };
  }
  if (!detectVsCode(env)) {
    return { action: 'skipped', reason: 'not_vscode' };
  }

  const bin = opts.throughlineBin !== undefined
    ? opts.throughlineBin
    : resolveThroughlineBin();
  if (!bin) {
    return { action: 'skipped', reason: 'no_bin' };
  }

  const vscodeDir = join(cwd, '.vscode');
  const tasksPath = join(vscodeDir, 'tasks.json');

  if (!existsSync(tasksPath)) {
    if (!existsSync(vscodeDir)) mkdirSync(vscodeDir, { recursive: true });
    const obj = { version: '2.0.0', tasks: [buildMonitorTask(bin)] };
    atomicWrite(tasksPath, JSON.stringify(obj, null, 2) + '\n');
    return { action: 'created', path: tasksPath };
  }

  const text = readFileSync(tasksPath, 'utf8');

  if (detectJsoncFeatures(text)) {
    emitJsoncGuidanceOnce(vscodeDir);
    return { action: 'skipped', reason: 'jsonc_unsupported', path: tasksPath };
  }

  let obj;
  try {
    obj = JSON.parse(text);
  } catch {
    return { action: 'skipped', reason: 'parse_error', path: tasksPath };
  }

  if (hasMonitorTask(obj)) {
    return { action: 'already_present', path: tasksPath };
  }

  const indent = detectIndent(text);
  const nextObj = {
    ...obj,
    version: obj.version ?? '2.0.0',
    tasks: [...(Array.isArray(obj.tasks) ? obj.tasks : []), buildMonitorTask(bin)],
  };
  atomicWrite(tasksPath, JSON.stringify(nextObj, null, indent) + '\n');
  return { action: 'merged', path: tasksPath };
}
